version: "3.9"

services:
  backend:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench
    command: >
      bash -c "
      bench start
      "
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
      ZALO_APP_ID: ${ZALO_APP_ID}
      ZALO_SECRET: ${ZALO_SECRET}
      ZALO_OA_ACCESS_TOKEN: ${ZALO_OA_ACCESS_TOKEN}
      GROUP_ID_ZALO: ${GROUP_ID_ZALO}
      ZALO_REDIRECT_URI: ${ZALO_REDIRECT_URI}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
      - redis-cache
      - redis-queue

  create-site:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: "no"
    working_dir: /home/frappe/frappe-bench
    entrypoint: bash -c
    command: >
      sleep 15;
      if [ ! -d "sites/${SITE_NAME}" ]; then
        bench new-site ${SITE_NAME}
        --admin-password=${ADMIN_PASSWORD}
        --db-root-password=${MYSQL_ROOT_PASSWORD}
        --install-app erpnext;
      else
        echo "Site exists";
      fi
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  frontend:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: unless-stopped
    command: nginx-entrypoint.sh
    ports:
      - "80:8080"
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${SITE_NAME}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - backend
      - websocket

  websocket:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench
    command: node apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  queue:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench
    command: bench worker
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  scheduler:
    image: frappe/erpnext:v15
    networks:
      - frappe_network
    restart: unless-stopped
    working_dir: /home/frappe/frappe-bench
    command: bench schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

volumes:
  db-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge